### ISSUE TITLE
Create lecture on Git and GitHub

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#1]
Remix material that people have already created to produce a 90-minute introduction to Git and GitHub. Length and depth should be similar to [existing Subversion material](http://software-carpentry.org/4_0/vc/).

**Comment by wking** [comment]
I've collected links to previous suggestion from tutors@ [here](https://github.com/wking/dvcs-content/blob/wking/README.md).

**Comment by wking** [comment]
Where is this going to live, and what format will it be in?  Are we looking for more LibreOffice slides to match the existing Subversion material?  That seems to run contrary to #5:

On Wed, Dec 12, 2012 at 08:18:29AM -0800, Greg Wilson wrote:

> On 2012-12-12 11:16 AM, Matt wrote:
> 
> > @gvwilson https://github.com/gvwilson can correct me, but I think we
> > are completely done with ODP/PPT formats. New content will be in
> > something else (e.g. IPython Notebooks for anything Python related).
> 
> That is my strong preference, though #include years of discussion about
> what's wrong with current-generation HTML as a slideshow format...

On the other hand, I'm not sure what the alternative is.  If I'm going to take a stab at synthesizing the Git material, what format would people like to see?

**Comment by gvwilson** [comment]
Still TBD.

**Comment by wking** [comment]
On Thu, Dec 20, 2012 at 07:32:46AM -0800, Greg Wilson wrote:

> Still TBD.

Perhaps a blocking "Decide on lecture format of the future" issue
would help focus discussion in this direction?

**Comment by jiffyclub** [comment]
+1 to the "decide on lecture format" issue, though I'm actually in favor of just letting people submit whatever the hell they want as long as it's not large binary files.

**Comment by wking** [comment]
On Thu, Dec 20, 2012 at 07:53:11AM -0800, Matt wrote:

> I'm actually in favor of just letting people submit whatever the
> hell they want as long as it's not large binary files.

I agree with this so much that I don't even have a preference for
format ;).  I just want someone to tell me what format to use when
coding up a Git/GitHub lecture pull request.  Presumably anything
other than Jinja/HTML will need compile.py support, but there are no
recent non-ODP lectures to use as examples.

**Comment by gvwilson** [comment]
Working on it...
G

**Comment by jiffyclub** [comment]
I'd assume this will actually go into the boot-camps repo, so for simplicity you could just stick to a lesson plan in Markdown for starters.

**Comment by wking** [comment]
On Thu, Dec 20, 2012 at 10:30:08AM -0800, Matt wrote:

> I'd assume this will actually go into the boot-camps repo, so for
> simplicity you could just stick to a lesson plan in Markdown for
> starters.

Ah, I think there will be entries in the website repository (with
other lecture material), in the boot-camps repository, and in the
assets repository (as a book chapter/section).  Since this issue is
against the website repository, I'd assumed it was calling for a
lecture entry in the website repository.

There are a number of good Git tutorials already in Markdown that are
ready for the boot-camps repository.  As far as I know, they are all
blocking on some sort of confirmation of the build toolchain for
boot-camps.  The current status of this on gits@ seems to be
Jekyll/Markdown vs. GitHub-browser/Markup, but this issue is probably
not the place to continue that discussion ;).

**Comment by gvwilson** [comment]
Please let's defer this until I've had a chance to think about formats 
for non-Python teaching material going forward.
