### ISSUE TITLE
Create media-based introduction to Python programming

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#10]
Write an alternative introduction to programming in Python that uses image manipulation for examples.
- Build on top of [Michael Hansen's simple media library](https://github.com/synesthesiam/skimage)

**Comment by ethanwhite** [comment]
I have to admit I'm not sold on this yet. My take away from the Guzdial article was that it was the giving students something they can identify with that was important ("Students found the new course more relevant and compelling"), not the image based stuff _per se_. Media-based approaches make sense as a general topic that lots of generic undergraduates would be interested in and be able to identify with, but since most of our learners won't be doing image manipulation I'm not sure that it will have the same effect. Given that this is potentially a lot of effort it seems like it might be worth thinking about this for a bit before committing to the effort.

EDIT: It was the Guzdial article.

**Comment by jkitzes** [comment]
I agree strongly with Ethan's comment - I suspect that our time on this topic would be better spent developing domain-specific exercises for different audiences, rather than changing our "generic" lessons over to a media focus. For my own field, for example, I think [using logistic population growth models](http://nbviewer.ipython.org/urls/raw.github.com/swcarpentry/2012-11-scripps/master/python/python-full.ipynb) to teach ecologists programming would be more "relevant and compelling" than using generic images or sounds.

**Comment by wking** [comment]
See also, PR #333.
