### ISSUE TITLE
Create blog index by author and topic

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#161]
We currently index by date alone; need to have an index by author, and another by topic.

**Comment by wking** [comment]
I'm still not entirely convinced that rolling our own blogging engine
is the way to go here.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 08:03:40AM -0500, Greg Wilson wrote:

> …did you ever look at Pelican (a Python compile-your-blog tool)?
> Jon P. and I explored using it to build our website instead of
> rolling our own, but it looked like the hard part --- extracting and
> collating metadata --- wasn't handled at all, so building the
> extensions we'd need would be just as much work as what we're doing
> now.

It looks like arbitrary metadata is pretty easy to use [1](http://docs.getpelican.com/en/3.1.1/faq.html#can-i-use-arbitrary-meta-data-in-my-templates).  Also, the
engine building the `blog/` directory does not need to be the same as
the engine building the rest of the site.  One problem with the
current `compile.py` is that one a page declaring a `subfile` or
`subglob` gets easy access to that (group of) page(s).  This leads to
hackery like the existing `create_rss` and `ICalendarWriter` in
`compile.py`, which each use their own `Instances` hack to get access
to a particular group of pages.  `blog/index.html` is already mostly
calendar indexing (because splitting that index out into
`blog/calendar-index.html` or some such would require a new
`compile.py` hack).  Adding more index styles would require either
more `compile.py` hacks, or a fairly thorough `compile.py`
restructuring.

I'll give Pelican another look and see how easy it is to stretch over
our needs…

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 01:22:59PM -0800, Greg Wilson wrote:

> On 2013-01-03 8:25 AM, W. Trevor King wrote:
> 
> > On Thu, Jan 03, 2013 at 08:03:40AM -0500, Greg Wilson wrote:
> > 
> > > …did you ever look at Pelican (a Python compile-your-blog tool)?
> > > Jon P. and I explored using it to build our website instead of
> > > rolling our own, but it looked like the hard part --- extracting and
> > > collating metadata --- wasn't handled at all, so building the
> > > extensions we'd need would be just as much work as what we're doing
> > > now.
> > 
> > It looks like arbitrary metadata is pretty easy to use [1].
> 
> But only within the same doc --- as soon as I want doc X to use metadata 
> from doc Y (e.g., to use information about particular bootcamps in 
> bootcamps/index.html), things seem to get a lot nastier.

This seems like a minor patch on Pelican.  I'll see if I can get it
working.

> > Also, the engine building the `blog/` directory does not need to
> > be the same as the engine building the rest of the site. One
> > problem with the current `compile.py` is that one a page declaring
> > a `subfile` or `subglob` gets easy access to that (group of)
> > page(s). This leads to hackery like the existing `create_rss` and
> > `ICalendarWriter` in `compile.py`, which each use their own
> > `Instances` hack to get access to a particular group of pages.
> 
> Agreed. We could solve that by reading child pages multiple times, but 
> that slows down compilation (and feels clumsy).

Or you could have an engine that gives each template access to the
consolidated data.  Fast and elegant ;).

> > `blog/index.html` is already mostly
> > calendar indexing (because splitting that index out into
> > `blog/calendar-index.html` or some such would require a new
> > `compile.py` hack). Adding more index styles would require either
> > more `compile.py` hacks, or a fairly thorough `compile.py`
> > restructuring.
> 
> In my defense, some of that hackery has to be in anything we use, e.g., 
> sorting bootcamps by start date, or gathering excerpts from 4_0 lessons...

Possibly ;).  I'm posting my Pelican translation in my `pelican` branch:

  https://github.com/wking/swc-website/tree/pelican

Anyone who's interested can chip in with suggestions/patches.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 04:49:09PM -0500, W. Trevor King wrote:

> On Thu, Jan 03, 2013 at 01:22:59PM -0800, Greg Wilson wrote:
> 
> > On 2013-01-03 8:25 AM, W. Trevor King wrote:
> > 
> > > Also, the engine building the `blog/` directory does not need to
> > > be the same as the engine building the rest of the site. One
> > > problem with the current `compile.py` is that one a page declaring
> > > a `subfile` or `subglob` gets easy access to that (group of)
> > > page(s). This leads to hackery like the existing `create_rss` and
> > > `ICalendarWriter` in `compile.py`, which each use their own
> > > `Instances` hack to get access to a particular group of pages.
> > 
> > Agreed. We could solve that by reading child pages multiple times, but 
> > that slows down compilation (and feels clumsy).
> 
> Or you could have an engine that gives each template access to the
> consolidated data.  Fast and elegant ;).
> 
> > > `blog/index.html` is already mostly
> > > calendar indexing (because splitting that index out into
> > > `blog/calendar-index.html` or some such would require a new
> > > `compile.py` hack). Adding more index styles would require either
> > > more `compile.py` hacks, or a fairly thorough `compile.py`
> > > restructuring.
> > 
> > In my defense, some of that hackery has to be in anything we use, e.g., 
> > sorting bootcamps by start date, or gathering excerpts from 4_0 lessons...
> 
> Possibly ;).  I'm posting my Pelican translation in my `pelican` branch:
> 
>   https://github.com/wking/swc-website/tree/pelican

I think my Pelican proof of concept is now feature-complete.  What's
left to do:
- Translate content to Markdown (or ReST).  In the proof of concept, I
  just used the “HTML is valid Markdown” loophole and changed the
  extensions ;).
- Design a template system and styling.  I don't expect translating
  this from the current stuff to be too difficult, since they're both
  Jinja-based.  The proof of concept theme is mostly borrowed under
  the Apache license, so we may want to stick my changes on top of a
  base with another license.
- Check that not too much broke ;).  For example, both bootcamps and
  blog posts are Pelican articles, so they will be using the same URL
  scheme.  The current site uses `bootcamps/YYYY-MM-SLUG` for one and
  `blog/YYYY/MM/SLUG` for the other.

This sort of major technical overhaul will probably take me a while,
so if anyone else wants to take over now that the trail is clear, I'd
be happy to have some assistance.

Moving forward on this also assumes that we like Pelican better than
all the other blog engines, of which I expect quite a few can handle
our requirements.  This might be worth a wider tutors@ discussion, but
the last time I tried to start one, it fizzled fairly quickly ;).

**Comment by wking** [comment]
I've posted my gently patched fork of Pelican on

  https://github.com/wking/swc-website/tree/pelican-fork

I expect the three PRs it contains (getpelican/pelican#661,
getpelican/pelican#662, and getpelican/pelican#663) will be accepted
shortly, since I didn't do anything too drastic.

**Comment by gvwilson** [comment]
Hi Trevor,

> I think my Pelican proof of concept is now feature-complete. What's
> left to do:
> You type fast :-)
> - Translate content to Markdown (or ReST). In the proof of concept, I
>   just used the “HTML is valid Markdown” loophole and changed the
>   extensions ;).
>   Not worth doing.
> - Design a template system and styling. I don't expect translating
>   this from the current stuff to be too difficult, since they're both
>   Jinja-based. The proof of concept theme is mostly borrowed under
>   the Apache license, so we may want to stick my changes on top of a
>   base with another license.
>   Er, OK, I guess I'd better check the branch.  (I'd've thought this was 
>   the first thing...)
> - Check that not too much broke ;). For example, both bootcamps and
>   blog posts are Pelican articles, so they will be using the same URL
>   scheme. The current site uses `bootcamps/YYYY-MM-SLUG` for one and
>   `blog/YYYY/MM/SLUG` for the other.
>   Is there an extension point in Pelican for setting different URL slugs 
>   for different types of things?
>   This sort of major technical overhaul will probably take me a while,
>   so if anyone else wants to take over now that the trail is clear, I'd
>   be happy to have some assistance.
> 
> Moving forward on this also assumes that we like Pelican better than
> all the other blog engines, of which I expect quite a few can handle
> our requirements. This might be worth a wider tutors@ discussion, but
> the last time I tried to start one, it fizzled fairly quickly ;).
> I think this is a great opportunity for a fait accompli :-)
> Cheers,
> Greg

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 04:15:00PM -0800, Greg Wilson wrote:

> > - Translate content to Markdown (or ReST). In the proof of concept, I
> >   just used the “HTML is valid Markdown” loophole and changed the
> >   extensions ;).
> 
> Not worth doing.

Then we at least need to de-indent a bunch of book material so
Markdown doesn't decide it needs `<pre>` wrappers.

> > - Design a template system and styling. I don't expect translating
> >   this from the current stuff to be too difficult, since they're both
> >   Jinja-based. The proof of concept theme is mostly borrowed under
> >   the Apache license, so we may want to stick my changes on top of a
> >   base with another license.
> 
> Er, OK, I guess I'd better check the branch.  (I'd've thought this was 
> the first thing...)

Nothing interesting happens in the templates ;).  My changes on top of
the `bootstrap` template I started with were:
- theme/templates/map.html     | 11 +++++++++++
- theme/templates/authors.html | 11 +++++++++++
- theme/templates/tags.html    |  7 +++++--

Designing a template from one of the DWTFYWTPL-based themes will
probably not be hard, but styling websites is not something I'm good
at.

> > - Check that not too much broke ;). For example, both bootcamps and
> >   blog posts are Pelican articles, so they will be using the same URL
> >   scheme. The current site uses `bootcamps/YYYY-MM-SLUG` for one and
> >   `blog/YYYY/MM/SLUG` for the other.
> 
> Is there an extension point in Pelican for setting different URL slugs 
> for different types of things?

Not that I found ;).  It probably wouldn't be hard to add, but why
force inconsistency?  We'll have a fixed number of old URLs to
grandfather in with rewrite rules.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 06:42:48PM -0500, W. Trevor King wrote:

> I've posted my gently patched fork of Pelican on
> 
>   https://github.com/wking/swc-website/tree/pelican-fork
> 
> I expect the three PRs it contains (getpelican/pelican#661,
> getpelican/pelican#662, and getpelican/pelican#663) will be accepted
> shortly, since I didn't do anything too drastic.

My Pelican fork is now much more extensivly patched.  Pelican has
currently frozen PRs until they merge their py3k branch (maybe
tomorrow :), but I'm not sure when my patches will bubble up to the
top of the backlogged queue.

Anyhow, my current `pelican-fork` builds my `pelican` branch of the
SWC website, and it has blog indexes by author (`output/authors.html`)
and topic (`output/tags.html`).  Now I just need to go through and
implement all the other stuff that goes on in `compile.py`…

**Comment by wking** [comment]
I think I need some guidance on how to handle in-Article Jinja.
Currently bootcamps use `{% include "_what.html" %}`,
`{{eventbrite(…)}}`, … and blog posts use `{{youtube(…)}}`.
However, when I started the Pelican translation, I made both
categories `Article` instance, as they were the most blog-post-y.
Unfortunately, Pelican is treating the post content as Markdown +
metadata, which means Jinja in the post content is left
unexpanded in the blog posts themselves, and presumably also in
their feeds (cf. #159, #166).

Possible solutions:
1. Add a new “Jekyll + Markdown” Article type.  I'm not sure what
   the extension would be, but the file would get read in as a
   Jekyll template (with the usual Pelican context), expanded,
   converted from Markdown to an HTML content chunk, and then
   inserted into the `article.html` theme template to create the
   full page.  This would take the least amount of work, but I'm
   not overjoyed with the end product.
2. Use ReST instead of Markdown/HTML if you need something fancy.
   Pelican already provides a number of ReST
   directives (`pelican/rstdirectives.py`), and this is exactly
   the sort of thing that ReST is good at.  On the other hand,
   that means a number of pages need to be converted from their
   current Markdown/HTML to ReST.  I think this is the way to go,
   but I want to get an official blessing before putting in a
   bunch of potentially controversial work.

Preferences?  Other alternatives?  @gvwilson?

**Comment by gvwilson** [comment]
> Currently bootcamps use `{% include "_what.html" %}`,
> `{{eventbrite(…)}}`, … and blog posts use `{{youtube(…)}}`.
> However, when I started the Pelican translation, I made both
> categories `Article` instance, as they were the most blog-post-y.
> Unfortunately, Pelican is treating the post content as Markdown +
> metadata, which means Jinja in the post content is left
> unexpanded in the blog posts themselves, and presumably also in
> their feeds (cf. #159, #166).
> 
> Possible solutions:
> 1. Add a new “Jekyll + Markdown” Article type. [details]
> 2. Use ReST instead of Markdown/HTML if you need something fancy. 
>    [details]
>    Can Pelican be extended with a "source is Jinja2" Article type?  Or is 
>    that the same as #1?

**Comment by wking** [comment]
On Sun, Jan 13, 2013 at 01:53:40PM -0800, Greg Wilson wrote:

> > 1. Add a new “Jekyll + Markdown” Article type. [details]
> > 2. Use ReST instead of Markdown/HTML if you need something fancy. 
> >    [details]
> >    Can Pelican be extended with a "source is Jinja2" Article type?  Or is 
> >    that the same as #1?

It's a bit different.  Pelican can already process Jinja templates (my
`TEMPLATE_PAGE_PATHS`).  However, all of Pelican's feed generation,
etc., is for the `Article` class, read in using the `*Reader`s from
`pelican.readers`.  There's currently no Jinja+HTML reader, but it
shouldn't be too hard to add one.  This is probably the best non-ReST
route.

**Comment by gvwilson** [comment]
Hi,

> It's a bit different. Pelican can already process Jinja templates (my
> `TEMPLATE_PAGE_PATHS`). However, all of Pelican's feed generation,
> etc., is for the `Article` class, read in using the `*Reader`s from
> `pelican.readers`. There's currently no Jinja+HTML reader, but it
> shouldn't be too hard to add one. This is probably the best non-ReST
> route.
> Please explore --- if it's pretty easy to do, I imagine other Pelican 
> users would find it helpful as well.

**Comment by wking** [comment]
On Sun, Jan 13, 2013 at 02:55:51PM -0800, Greg Wilson wrote:

> > It's a bit different. Pelican can already process Jinja templates (my
> > `TEMPLATE_PAGE_PATHS`). However, all of Pelican's feed generation,
> > etc., is for the `Article` class, read in using the `*Reader`s from
> > `pelican.readers`. There's currently no Jinja+HTML reader, but it
> > shouldn't be too hard to add one. This is probably the best non-ReST
> > route.
> 
> Please explore --- if it's pretty easy to do, I imagine other Pelican 
> users would find it helpful as well.

Done.

I think I'm getting a bit far ahead of `pelican/master`, so I'm going
to take a break until the Pelican folks can catch up a bit ;).  The
major parts of the Pelican-generated site are looking pretty good to
me.

Still todo:
- Poke around the `3_0` and `4_0` submodules.
- Audit for other broken stuff.

**Comment by gvwilson** [comment]
Will deal with it as part of the Pelican conversion.
