### ISSUE TITLE
Firefox add-on instruction should be "Web Developer" not "Tools"

### ISSUE THREAD

**Issue by rmdickson** [swcarpentry/DEPRECATED-website#184]
http://software-carpentry.org/setup/common.html says "When Firefox restarts, Select Tools => SQLite Manager", but this is unavailable in Firefox 17.0.1.  

Should read "When Firefox restarts,select Web Developer => SQLite Manager"

**Comment by ethanwhite** [comment]
This is actually a little bit OS dependent because Ubuntu by default doesn't use the big orange button in order to allow integration with it's HUD system, in which case it is located under Tools, but I definitely agree that this should be updated to the more common form perhaps with a parenthetical for Ubuntu users.

**Comment by wking** [comment]
I think this was one of the side effects of the whole “version numbers
are scary” mindset [1](https://bugzilla.mozilla.org/show_bug.cgi?id=678775) ;).

**Comment by wking** [comment]
Ethan's commit fixes this issue, but we forgot to close it until now.
