### ISSUE TITLE
Improve setup/installation instructions for workshop participants.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#2]
Reorganize and reformat setup & installation instructions for workshop participants. These should be organized as a grid (platform vs. tool), but also include a path (step 1, step 2, ...) for each platform. They should _not_ assume more information about things like environment variables than our participants have before taking our workshops.

**Comment by caitsydney** [comment]
If I make an entirely new .html page for reorganization, how do I include that file in "make check"?

**Comment by caitsydney** [comment]
Also, are we only using Mac and vm's now? (Not sure if SWC ever taught how to do all this on a PC without a VM)... So the PC and Unix install instructions would be similar/the same (with the exception of PC users needing to use something like VirtualBox), yes?

**Comment by gvwilson** [comment]
On 2012-12-14 8:59 PM, Caitlyn wrote:

> If I make an entirely new .html page for reorganization, how do I
> include that file in "make check"?

If you take a look in ./index.html, there are tags like:

```
 <meta name="subfile" content="bootcamps/index.html" />
```

There are similar tags in some other files, along with some like this:

```
 <meta name="subglob" content="*-*-*.html" />
```

which matches a bunch of files instead of a single one.  The 
bin/compile.py script that builds the web site follows these links 
recursively to figure out what to build.  If you want to add a new page, 
you can just add a subfile meta for it in the index.html page in its 
directory, or something like that.

There is one catch, though.  Right now, ./index.html refers to 
bootcamps/faq.html, while bootcamps/index.html only refers to the 
subglob mentioned above.  The reason is that when we compile 
bootcamps/index.html, we want to automatically create a list of past and 
future boot camps.  To do that, we need a list of all the pages that 
describe boot camps, and we don't want bootcamps/faq.html in the list. 
That's why we separate one-of-a-kind pages that happen to be in the same 
directory as glob-matched pages from those glob-matched pages.  It's a 
hack, but there didn't seem to be a clean alternative.
- Greg

**Comment by gvwilson** [comment]
Hoo boy --- no, we're still officially supporting Linux, Mac OS X, and 
Windows, with Git Bash or Cygwin on the latter.  We'll talk more at 
Wednesday's meeting about what we do in 2013 --- there are no good 
answers :-(

**Comment by caitsydney** [comment]
Okay. I'm doing the Mac and Linux stuff first. I'll worry about Windows after Wednesday's meeting I think.

@gvwilson (and others)
Look at this doc and let me know your thoughts? You should be able to edit directly, just comment here when you've had the chance. It's a draft of the navigation grid. I want some feedback before I get too far with the index.html page, cause I want to make sure I cover everything. In the mean time, I'm working on the appropriate subpages.
https://docs.google.com/document/d/11woqfya049blB58f6ED5tSt7xgtjGFLqEeO_gxunc4I/edit

**Comment by gvwilson** [comment]
I like the grid idea a lot. I do _not_ like the idea of Unix VMs on 
Windows machines, but I realize other people do, and I realize that's a 
quibble compared to the overall grid idea.

**Comment by caitsydney** [comment]
So, then you do want to have full PC install instructions, yes? Cygwin and all that, like you mentioned before. Would a VM be a fourth OS column, or would it be combined with the Linux col? I'm going to do a pull request tonight for my forked repo so I can get some feedback on what I've done so far. It's not ready for merging (at all), but I want your opinions... That is ok etiquette for a pull request, right? If not, what is the alternative? Just ask you directly to look at it?

**Comment by gvwilson** [comment]
Best thing right now is to fill in the Mac and Linux columns, and leave 
the whole vexed question of Windows 'til after Wednesday's call...

**Comment by jiffyclub** [comment]
A pull request is fine when looking for feedback on the work you've already done. Just make clear it's not ready so that hopefully no one will merge it.

**Comment by wking** [comment]
On Fri, Dec 14, 2012 at 07:10:36PM -0800, Matt wrote:                                                                      

> A pull request is fine when looking for feedback on the work you've already done. Just make clear it's not ready so that hopefully no one will merge it.

The review PR surfaced briefly as #93, but work seems to have stalled out.  In order to reduce the number of balls we're juggling, it would be nice to wrap this up somehow.  As encouragement, I've posted swcarpentry/boot-camps@001b57b as part of my test script PR swcarpentry/boot-camps/issues/12.  As an example of what I'm looking for, see swcarpentry/boot-camps@38520f9, which links users to places like:                                                      

```
http://software-carpentry.org/setup/ubuntu.html#emacs
```

if we can't detect Emacs on an Ubuntu system (and they don't have another editor installed).  I'm looking for a consistent URL scheme to construct a link for a student missing package `$x` on system `$y` (`emacs` and `Ubuntu` in the example above) [1](https://github.com/swcarpentry/website/issues/39#issuecomment-11857084).

Is there any chance of this setup-instruction-reorganization leading to something like this URL scheme in the near future? ;)

If not, would people mind if I just patched anchor IDs into the existing setup pages as a stop-gap until the full restructuring lands?
