### ISSUE TITLE
Navbar getting crowded

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-website#219]
With the extra space needed for dropdown carets in the navbar it's started to get crowded at smaller screen widths:

![Screen shot 2013-01-15 at 4 33 53 PM](https://f.cloud.github.com/assets/920492/69367/885c9884-5f5b-11e2-9c22-f06d1626f3a4.png)

We might consider removing the "Home" link or moving "License" under "About".

**Comment by ethanwhite** [comment]
I think moving "License" under "About" seems like a good idea anyway.

**Comment by pipitone** [comment]
+1

It's also already linked to in the footer as well.

**Comment by gvwilson** [comment]
I would rather get rid of 'Home' (since the logo gets us there) --- 
licensing needs to be very (very) easy to find, for a whole bunch of 
reasons.
Alternative: replace the CC-BY logo in the bottom left with one of those 
rounded white-on-blue box icons Matt's so fond of, and call it 'License'.
Or use a smaller font for menu items?
- G

**Comment by jiffyclub** [comment]
There's no reason we can't have a "About > License" _and_ the CC-BY image _and_ a footer label all linking to the license. (_And_ remove "Home"...)

**Comment by pipitone** [comment]
@jiffyclub does 8faa585 make this ready to close?

**Comment by jiffyclub** [comment]
Yes, my bad for not attaching it to this issue.
