### ISSUE TITLE
Blog comments appear missing

### ISSUE THREAD

**Issue by dmcglinn** [swcarpentry/DEPRECATED-website#220]
I wrote a blog post for software carpentry back on 2012-05-31 which received several comments shortly after posting.  Here is the current link:

http://software-carpentry.org/blog/2012/05/dictionaries-are-a-scientists-friend.html

I noticed that these comments no longer are associated with the post. I'm not sure if this a general problem where all the blog posts lost their comments or not.  If possible it would be great to associate the old posts with their old comments.

**Comment by gvwilson** [comment]
Hm --- we did spot checks when we switched to Disqus, and it looked like 
comments had been kept.  I'll check against the last saved copy of the 
WordPress database.

**Comment by pipitone** [comment]
So, I did some digging.  All our comments from the wordpress site _are_ in Disqus, but we've changed the URLs to the blog posts, and so Disqus isn't displaying them.  An example of our old blog URL: 

```
http://software-carpentry.org/2012/05/dictionaries-are-a-scientists-friend.html
```

and our new blog URL:

```
http://software-carpentry.org/blog/2012/05/dictionaries-are-a-scientists-friend.html
```

Note the /blog/ bit in the new URLs. 

Because Disqus can't import from its export format (I know.. brain damaged), here's one proposal: 
1. Use the WP Disqus plugin to _sync_ the existing comments back to a new wordpress install.
2. Export the comments to a WXR file using the standard wordpress site exporter.
3. Replace old blog URLs with the new ones in the WXR file
4. Nuke all of the comments in Disqus
5. Import the modified WXR file with the fixed comments.

**Comment by gvwilson** [comment]
My first question is, How important is this really?

**Comment by pipitone** [comment]
Depends how much we care about old comments, I suppose.

Seems like a strange thing to do to just ditch them... I mean, why not
ditch all of the old content as well, right?

**Comment by gvwilson** [comment]
OK, if you think it's worth the effort (and you're sure we won't lose 
any of the current Disqus comments), go for it.
- G

**Comment by gvwilson** [comment]
@pipitone any progress on this?

**Comment by pipitone** [comment]
Turns out things are much simpler than I had thought.  Disqus has [migration tools](http://software-carpentry.disqus.com/admin/tools/migrate/). One option is to have disqus crawl your site and update the post URLs. Nice.  I've kicked that off so perhaps in a few hours we'll see comments return.  If not, we can upload a CSV file that maps old URLs to new ones, so I'll give that a go.

**Comment by pipitone** [comment]
Comments are back!
