### ISSUE TITLE
Store contact information and other workshop details in a secure, shareable way

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#43]
@gvwilson currently stores information on past workshops (e.g., participants names and email addresses, instructors t-shirt sizes, etc.) in an SQLite database stored in a private Subversion repository. We need something better that:
- supports versioned sharing
- is secure
- doesn't violate any privacy protection laws

**Comment by wking** [comment]
Cross-posted from issue #14

On Mon, Dec 10, 2012 at 04:15:14PM -0500, W. Trevor King wrote:

> On Mon, Dec 10, 2012 at 01:06:43PM -0800, npch wrote:
> 
> > Question: are we going to be collecting and storing details of
> > instructors, helpers and organisers in a "standard" format for each
> > bootcamp?
> 
> +1 for structured data.  Boot camp YAML front matter in
> boot-camps/gh-pages would be a good place for this.  If this
> information is not going into the websites or related content, storing
> it somewhere else may be ok.  I'm not sure it's worth the mental
> overhead of having two (or more) places where boot-camp details are
> kept.

**Comment by drj11** [comment]
I have used a private bitbucket repo (they're free for a small number, unlike github) for things like this in the past.  works well.

If you want it mergeable, the CSV output from sqlite is probably okay.

**Comment by wking** [comment]
More guidelines about the target level of security would be useful.
For example:
1. Can we trust BitBucket?
2. Can we trust DreamHost (or wherever sw-c.o is hosted)?
3. Can we trust unencrypted email?

Let's worry about securely sharing something (even the raw SQLite DB)
before we start worrying about versioning it.

**Comment by gvwilson** [comment]
I have a file containing names and email addresses for boot camp 
participants, and home addresses for instructors.  Going forward, we'll 
also need to store things like travel expense claims.  Agreed that 
versioning is a secondary concern, but I would like offline editing to 
be possible.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 07:02:39AM -0800, Greg Wilson wrote:

> I have a file containing names and email addresses for boot camp 
> participants, and home addresses for instructors.  Going forward, we'll 
> also need to store things like travel expense claims.

So are all of the sharing options I listed earlier [1](https://github.com/swcarpentry/website/issues/43#issuecomment-11791668) acceptable?

> Agreed that versioning is a secondary concern, but I would like
> offline editing to be possible.

If you share the SQLite database (or it's dump) somehow, interested
(and authorized) parties could keep local copies and send you changes
(as SQL commands).  You integrate those changes (and your own local
changes), and periodically share the new database.

This sounds easy enough, since remote changes are likely to be low
volume.  Using a VCS for the sharing would make it easier for others
to stay up to date, but if you can't trust BitBucket or DreamHost,
finding a way for you to publish your repository will be difficult.

**Comment by gvwilson** [comment]
Our existing mechanism will suffice for this funding round.
