### ISSUE TITLE
Develop generic timeline for planning a boot camp

### ISSUE THREAD

**Issue by gonuke** [swcarpentry/DEPRECATED-website#47]
While every case will be a little different, it would be useful to develop/share best practices for planning a workshop.   In particular, what is a the recommended/preferred number of days/weeks/months prior to the event to have finalized detail x/y/z....

**Comment by caitsydney** [comment]
Based off of the How to Run a Boot Camp (bootcamps/how-to.html), I made a table timeline. Code is here: https://github.com/picken19/swc

Is this what you had in mind? Less detailed, more detailed?

**Comment by gvwilson** [comment]
Good starting point --- as soon as we finish switching to Git 
(tomorrow?) let's get this merged.
Thanks!
Greg

**Comment by wking** [comment]
On Thu, Dec 13, 2012 at 07:01:43AM -0800, Caitlyn wrote:

> Based off of the How to Run a Boot Camp (bootcamps/how-to.html)

Since there will be a fair amount of overlap, can we just restructure
`how-to.html` to make the timeline information more explicit?  Perhaps
we just need checklist entries that go further into the pre-workshop
time period (no anchors in how-to.html, so I can't link directly to
the “Checklists” section).

**Comment by gvwilson** [comment]
Seems sensible --- I've assigned this to @amyrbrown to consolidate.
