### ISSUE TITLE
Test installation of Enthought Canopy + extras

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#476]
Please add comments to this ticket to tell us what platforms you've installed Enthought Canopy on (https://enthought.com/products/canopy/), and what other packages you've installed with it --- we're particularly interested in Bash, Git, SQLite, and Pandas.

**Comment by ethanwhite** [comment]
I have successfully installed Canopy Express (the free version) on Windows 7 32-bit and 64-bit (1 machine each). I also installed msysgit (GitBash) on both machines and everything worked seamlessly with no additional effort (including launching nosetests, ipython, and ipython notebook from GitBash).

Pandas does not come pre-installed, but can be added using Canopy's built-in, graphical, package manager with a couple of clicks.

**Comment by jiffyclub** [comment]
I've tested it out on Mac OS 10.8 and it works. In good news the installation is less intrusive than their old installers and no longer requires an administrative password to install. It's not necessary to use the command line to install or configure if the user's environment is compatible with the installer's assumptions. At the command line they are using virtualenv to put the user into an isolated environment, at least on Mac. Or at least they've installed a virtualenv activation script, virtualenv itself is not installed.

I don't have much to say about the IDE. It's not something I would use for work or teaching. It seems pretty "lite", without the features of my text editor or the richness of the Notebook.

My one big beef with Enthought is that they are very keen to sign you up for an account (I guess to get your email address?), so they put limits on the packages you can install without signing up with them. Their graphical package manager will let you install pandas, but you want to install a free community package that has nothing to do with Enthought like pytest, basemap, or numexpr? Sorry, gotta sign up. That really bugs me.

**Comment by jiffyclub** [comment]
One thing I haven't been able to figure out is what versions of Mac OS X Canopy is compatible with. Doesn't seem to be anywhere on their site. Maybe that means all of them?

**Comment by ethanwhite** [comment]
> I don't have much to say about the IDE. It's not something I would use
> for work or teaching. It seems pretty "lite", without the features of my text
> editor or the richness of the Notebook.

I consider this a bonus in the classroom.

> My one big beef with Enthought is that they are very keen to sign you up for an account

Agreed, but for something that works across operating systems without a lot of hassles that's a small price to pay (especially since most people won't need to pay it)

> Their graphical package manager will let you install pandas,
> but you want to install a free community package that has nothing to do
> with Enthought like pytest, basemap, or numexpr? Sorry, gotta sign up.

Or you can just use easy_install/pip, which is what you'd have to do with other installations anyway.

**Comment by jiffyclub** [comment]
Actually, you have to `easy_install pip` first, it doesn't ship with it. That's a pretty bad oversight right there. :wink:

I don't think the IDE has any advantages over the Notebook for teaching. How do you consecutively execute two unrelated commands? You'd have to type them in the IPython console at the bottom but then you don't get any of the benefits of the Notebook. You need that interactive component and why settle for console IPython when you've already installed the Notebook?

**Comment by ethanwhite** [comment]
> I don't think the IDE has any advantages over the Notebook for teaching. 

No disagreement here, but it's a nice backup and a nice gateway IDE for folks that want one. I actually included all of that stuff because you've previously mentioned wanting a code aware editor [1] and this has one baked in without any additional install.

> How do you consecutively execute two unrelated commands?

There is a run selection option if you actually want one. 

[1] https://github.com/swcarpentry/website/pull/335#issuecomment-14383620

**Comment by jiffyclub** [comment]
Good point about the code editor. You can even launch it from the command line, though it blocks the terminal. (Necessitating the introduction of `&`.)

But I'm actually moving to the Notebook for when I teach modules and scripts. I used to go back to command line/text editor but I get so many complaints about the amount of window switching required that I'm going to use the Notebook and the `%%file` magic next time.

**Comment by jiffyclub** [comment]
All my criticisms aside, though, the fact that Canopy works out of the box on Windows pretty much means we have to use it. Can anyone test on Windows XP/8? Testing on older versions of Mac OS X would be good too. And Linux.

**Comment by pipitone** [comment]
I just did a installation of Canopy 32bit on a fresh Windows XP image.  The
installation went fine, but when I attempt to start the Canopy GUI, Package
Manager, or Code Editor (via clicking on the icon/start menu entires, or
command line) ... absolutely nothing happens.

I'll keep poking around.

**Comment by jiffyclub** [comment]
What about running things like ipython from Git Bash?

**Comment by katieirenec** [comment]
I installed Canopy on my MacBook with Mac OS 10.6, which was very easy. I made a new account for a friend, and it took about 8 minutes for the account verification email to arrive. Hopefully it won't be too much longer for others, becoming a bottleneck.

A couple inconveniences I've noticed so far:
- Canopy and previously installed modules don't seem to play well together, maybe because of the virtualenv Matt mentioned? I had pandas already installed by Anaconda, but `import pandas` didn't work in Canopy's Python. So I tried `pip install pandas` at the shell to see what would happen. Pip said pandas was already in ~/Applications/anaconda/lib/python2.7/site-packages and didn't install anything. Installing pandas with Canopy's GUI solved the problem, though I got some confusing "page not found" messages until I logged in. I feel like people will be confused why the stuff they already installed doesn't work.
- Why in the world would they add "(Canopy 64bit)" to the beginning of my bash prompt!? I'm not sure how to get rid of it besides modifying ~/Library/Enthought/Canopy_64bit/User/bin/activate.
  ![Screen shot 2013-04-11 at 11 09 56 PM](https://f.cloud.github.com/assets/3497707/374746/1a140caa-a3a7-11e2-88f4-1c4dd57df3e1.png)

Edit: I guess all these things stem from my lack of knowledge about virtualenv. An explanation of the levels of Canopy [here](http://stackoverflow.com/questions/15942438/display-of-canopy-on-command-line/15966112#15966112).

**Comment by jiffyclub** [comment]
@katieirenec: The `(Canopy 64bit)` in the prompt is something virtualenv does. It's so you know which virtualenv you're in (because you may potentially have several).

The problems you saw in the first point are because Canopy doesn't come with `pip`. When you typed `pip install pandas` it actually ran the `pip` in Anaconda because that was the first `pip` your system found. If you had first run `easy_install pip` to install `pip` into Canopy then `pip install pandas` would have installed pandas into Canopy.

**Comment by jiffyclub** [comment]
@ethanwhite & @pipitone, can you tell whether Canopy is using virtualenv on Windows, or does it have some other environment management solution? I don't even know whether you can use virtualenv on Windows.

**Comment by katieirenec** [comment]
@jiffyclub, I tried `easy_install pip` and then `pip install pandas` before installing pandas with the Canopy GUI, but I still got the same message about pandas already being installed with the Anaconda files. It's possible I overlooked something though.

In any case, maybe I can serve as a useful barometer for the reactions of bootcamp attendees who don't know about virtualenv :)

**Comment by jiffyclub** [comment]
@katieirenec: Another thing they don't tell you is that if you want to leave the Canopy environment you type `deactivate` (a virtualenv command), though if you don't have the `source /.../bin/activate` line in your `.profile` then getting a new shell would do the trick.

**Comment by ethanwhite** [comment]
> I just did a installation of Canopy 32bit on a fresh Windows XP image.
> The installation went fine, but when I attempt to start the Canopy GUI,
> Package Manager, or Code Editor (via clicking on the icon/start menu
> entires, or command line) ... absolutely nothing happens.

I just don't think that we can support XP anymore. That's supporting 4
different MS operating systems and even Microsoft is sunsetting security
patches.

**Comment by ethanwhite** [comment]
> @ethanwhite & @pipitone, can you tell whether Canopy is using virtualenv on Windows,
> or does it have some other environment management solution? I don't even know whether
> you can use virtualenv on Windows.

I don't believe so. It's just installing itself in it's own directory and adding that directory to
the front of the path.

**Comment by jiffyclub** [comment]
What's the percentage of people using XP these days? What about Vista? Did anyone ever even buy that?

I get at least on person per boot camp using Mac OS 10.5, which is totally unsupported now. VirtualBox doesn't even support it, I have to have them go download a couple year old version of VirtualBox so they can use the VM.

**Comment by ethanwhite** [comment]
Regarding the problems with needing to install Pandas:
1. Pandas will now be in new Canopy installs (http://lists.software-carpentry.org/pipermail/discuss-software-carpentry.org/2013-April/000340.html)
2. Canopy has a graphical package manager that easily installed Pandas for me. If we need to install packages this is probably easier to explain to novices than easy_install/pip.

**Comment by ethanwhite** [comment]
> What's the percentage of people using XP these days? What about Vista? Did anyone ever even buy that?

It's high in the global populace (I think it's actually the second most common OS), but lower in academia and with the MS dropping security patches I think it will disappear pretty quickly (from academia). I literally can't remember the last time I saw a Vista install anywhere.  Folks either went back to XP or upgraded to 7 as soon as it was available.

I've run into really out of date Linux distributions as well with ancient Python and Git installs. I just don't think we have the person power to support really out of date systems.

**Comment by ahmadia** [comment]
@jiffyclub - I haven't had a chance to try out Canopy but Anaconda has similar functionality and works across Windows, OS X, and Linux out of the box as well.  If it hasn't been working, can you point me to the thread where issues were raised?  I just ran three successful boot camps using Anaconda installs across all three platforms, I'm not opposed to using Canopy, but I'm wondering what the compelling reason to switch is.

**Comment by ethanwhite** [comment]
@ahmadia There have been issues with Anaconda for other folks. See @ctb's blog post (http://ivory.idyll.org/blog/2013-swc-arizona.html) to get started. Issues I remember include: 1. it doesn't put itself in the path on Macs and only does so optionally on Windows; 2. currently the Mac installer requires using the command line; 3. IPython doesn't run from GitBash out of the box (I think this may only be for 32-bit).

**Comment by ahmadia** [comment]
@ethanwhite - thanks for that, I'll be sure to point the Continuum folks at it.  As I mentioned before, I've had very good luck with Anaconda in the past, the only hiccup I've encountered in Windows is figuring out how to get IPython HTML Notebooks to launch in the right directory (create a shortcut).  

The fact that Anaconda doesn't put itself in your PATH/profile by default is a very good thing.  I wish more software packages did that, the very first thing I think we should be teaching in the shell is the concept of environment variables and the PATH variable.  But it sounds like this is a discussion for another thread...

**Comment by jiffyclub** [comment]
Also, Anaconda's `nosetests` doesn't run from GitBash.

**Comment by jiffyclub** [comment]
Nor is Anaconda on GitBash's `PATH`.

**Comment by goxberry** [comment]
@ahmadia As an expert user, not installing into the PATH is great. Teaching basic users, however? I'd rather there be a checkbox or flag I can tell people to select that will add the package to the appropriate part of the PATH. We spent quite a bit of time yesterday at the UCB workshop fixing people's PATH issues for Python packages, and just had to do it again for two people. Any time there are install issues, it holds up the class, and it ate a significant chunk out of the shell tutorial even though we showed up early. Since EPD switched the Canopy even though we told people to install the old EPD Free, we ran into tons of issues, and most of them were PATH-based.

As for teaching people about PATH first, that's another issue entirely.

**Comment by goxberry** [comment]
I messed up and posted this on the discuss list, so I apologize for the re-post, but here are the problems we ran into installing Canopy on Macs at UCB yesterday:
- To install it, after copying the Canopy.app to /Applications, you need to launch Canopy.app so that it installs all of the command-line Python tools.
- You also need to add the appropriate Canopy directory to your path, or source their activate script; people got hung up on this step
- Since this change occurred after our e-mails went out suggesting EPD, we should have included the install directions in http://docs.enthought.com/canopy/quick-start/install_macos.html on the Etherpad (obviously, similar instructions exist for other OSes)

**Comment by gvwilson** [comment]
Hi,

> As for teaching people about PATH first, that's another issue entirely.
> -1 to teaching PATH first (or even early): too many other conceptual 
> dependencies, not enough immediate gratification :-(
> - Greg (_hack_ _sniffle_ _wheeze_)

**Comment by ethanwhite** [comment]
>  As for teaching people about PATH first, that's another issue entirely.

I'm with Greg on this one, which emphasizes the value of having an installer that handles the path for us so that everything just works.

**Comment by goxberry** [comment]
I didn't want to threadjack, but I guess I already have...

> As for teaching people about PATH first, that's another issue entirely.

I was responding to the comment by @ahmadia:

> The fact that Anaconda doesn't put itself in your PATH/profile by default is a very good thing. I wish more software packages did that, the very first thing I think we should be teaching in the shell is the concept of environment variables and the PATH variable. But it sounds like this is a discussion for another thread...

So...yes, I completely agree with @ethanwhite and @gvwilson , and go even further. As a more expert user, I would rather have an installer insert itself into the PATH and undo it myself than be a basic user flailing around helplessly wondering why the thing I just installed doesn't work.

And in teaching this stuff, PATH is barely used in the Software Carpentry shell material online. It's towards the end because there's so much other stuff that gets used more. How often do users modify their PATH compared to a lot of the things taught earlier in the online shell material? Also, teaching PATH requires some of that earlier material anyway, like knowing about directory structure and permissions (if you can't execute it, putting it in your PATH is worthless) at the very least. Teaching PATH first is not the answer. I would rather sacrifice accuracy for simplicity, as long as the basic idea is right.

**Comment by teoliphant** [comment]
The default choice to not install Anaconda on the PATH by default is not appropriate for an introduction to Python.   We are fixing this in the next release.   Still, it's an easy thing to help people adjust to.   However, a bigger issue is the package manager which is getting over-looked in this discussion. 

The community has needed a cross-platform package management solution that works with multiple environments (unfortunately virtualenv makes analagous mistakes for packaging environments that distutils made for building tools).   We went to the packaging BOF at PyCon and they are still not even addressing the issues that conda is actually solving.   Conda is free, BSD licensed, and open source.   The repository format is open and it is easy to make your own Conda repositories, so that SWC could own it's own repository, fork from the free Continuum repository, and control the packages you want installed.    

You could even use conda to get all the other packages installed that you want installed and even build an installer with _all_ the packages you want.    

Obviously I'm an insider (but I'm also an insider in Canopy --- as it is exactly what I knew they were working on and a reason I left Enthought as I want the binaries to be freely available to everyone --- I'm glad I at least pushed for EPD Free / Canopy Express before I left).

SWC could be part of an effort that leads to a community-supported distribution that everyone can use and build from rather than supporting a single proprietary installer.

**Comment by gdevenyi** [comment]
@pipitone I just installed 32bit Canopy on my WinXP virtualbox VM (fresh fully updated windows) and everything seems to work fine.

**Comment by pipitone** [comment]
@gdevenyi Okay, that's good.  I'm also installing in a virtualbox VM, but still no love for me. Perhaps my image is broken somehow.  I'll try reinstalling and report back.

**Comment by jiffyclub** [comment]
@teoliphant, the issue for us is less what comes in the package as how the package integrates into the user's system. Anaconda and EPD both come with everything we need for a _typical_ boot camp. The real issue in our classrooms is whether users can use what's installed. (But don't get me wrong, I appreciate the openness of Anaconda and conda. :smiley:)

I think you are planning changes that will make Mac (and Linux?) installations easier by automatically modifying the user's `PATH`, etc. That's terrific, but Windows is our real challenge. Here's our optimal procedure there:
1. User installs something in the Git Bash/msysgit/mingw family (so they can use git from the command line and follow allong with the bash units).
2. User installs Anaconda.
3. Everything just works. python, ipython, pip, nosetests, py.test, etc.

In my experience number 3 has been the biggest challenge. Anaconda's bin directory isn't on the `PATH` and the various executables and scripts may or may not work. See @ethanwhite's Windows install script to see what he's had to do to shoe-horn Anaconda into compatibility with msysgit: https://github.com/swcarpentry/boot-camps/blob/master/setup/swc-windows-installer.py.

Thanks for listening and taking the needs of our super-novice students seriously. Let me know if I can help! (But be warned I'm useless on Windows.)

**Comment by embray** [comment]
Last I tried EPD it sometimes succeeded in changing the user's path, and sometimes didn't.  On Windows and OSX it also installed a bunch of shortcuts to things that they users don't need or that confuse the instruction effort.  For example, we come in telling them we're going to teach them "Python" (which some of them are passingly familiar with, some of them less so).  But then instead of telling them to "install Python" we tell them "install EPD" (Anaconda and any other distribution have this same problem though).  But then EPD installs Start Menu shortcuts and/or Application folder shortcuts on Macs with names like "Pylab".  Users end up clicking those and thinking that that's how they're supposed to start "Python".  "But why is it called 'Pylab' and not 'Python'?" they ask.    And unless we're specifically teaching this way of running Python to the entire class we have to run around telling them "No, don't run that thing.  You have to start this 'Terminal' program and then type 'ipython'", which only leads them to wonder "Why are you telling me like 3 ways to do what appears to me the same thing?"  Ugh.

I think, from my experience, Anaconda is a little more straightforward in this respect. Though automatically adding it to `$PATH`, `%PATH%`, etc. is pretty crucial, albeit potentially tricky business.

**Comment by embray** [comment]
Also following up on the comments of @goxberry and others, as an "expert" user I almost never touch environment variables and sometimes take great pains to avoid it (now that's of course something of an illusion since it amounts to having all my defaults set up in my .profile along with aliases to change stuff around in various ways when I need to).  Environment variables can be incredibly useful, but I'm not too keen on anything that requires throwing them in beginners' faces just in order to make things "just work".  That's one thing I like about virtualenv (though the problem with teaching virtualenv to beginners is that it's just a bit too magical).  I think the `conda` command works pretty well for that though.

**Comment by NelleV** [comment]
(I haven't read all the comments to this thread - it is a bit long).

We're currently running a bootcamp in Paris, and we had trouble with old version of mac os x (32bit) and Canopy. I haven't seen the error, nor helped debugging it, but it seems it doesn't play well with old version of mac os X.
I didn't ask people to install Canopy, but EPD Free: unfortunately, EPD free has now completely disappeared from the website, and as Anaconda works only for 64bits distributions.

We'll report the bug to one of Enthought's guy when we are done with the bootcamp. In general, I do have to admit that Canopy's UI is pretty nice. Unfortunately, it seems closed source, and I have trouble advocating for a closed source tool.

**Comment by jiffyclub** [comment]
There is also a Windows-only scientific Python distribution called [pythonxy](https://code.google.com/p/pythonxy/), has anyone taken a look at this?

**Comment by katieirenec** [comment]
I have a friend who is a graduate student in medical physics (think
radiation and MRIs), and he loves it. He used it extensively a year ago
while translating his MATLAB code into Python, and he really liked the
variable viewer/editor and ability to highlight a selection of code and run
it with F5. Writing this, I'm wishing there was a MacOS distribution ---
those are the features that I miss from MATLAB, and that I'm hoping will be
in Canopy someday. For scientific computing (and probably everything else),
having that ability to do a quick check of your variables' values can save
a lot of debugging time.

I can't double-check to make sure all the features he remembers are
still/actually in pythonxy, but for one scientist at least, it was a great
solution.

**Comment by jiffyclub** [comment]
@katieirenec, it sounds like you're describing the [Spyder IDE](https://code.google.com/p/spyderlib/) that comes with pythonxy. Spyder does have Mac distribution.

I'm curious whether someone could install pythonxy and then get to the stuff we need from Git Bash?

**Comment by onnodb** [comment]
I just installed Canopy 1.0.0.1160 on my Windows 7 laptop, and it's working pretty smoothly.
- Adding Python to the PATH is automatically taken care of by the installer, but you do need to log off and log in again to apply those changes.
- I tried running the iPython notebook, and this worked perfectly. (Version: 1.0dev)
- Pandas was easy to install using the GUI package manager, and seemed to work (I tried running some examples from the Pandas tutorial, and that worked fine). The current version is 0.10.1 --- not the most recent one, but still fairly recent. Is that good enough?

Overall, this seems like a pretty accessible package for novice, Windows-minded users. n = 1 though :)

EDIT: Btw, I'm quite experienced on Windows, so if there's any Windows issues or questions, I'd be happy to try and help :)

**Comment by jiffyclub** [comment]
And another option I just found out about, similar to pythonxy: https://code.google.com/p/winpython/.

**Comment by wking** [comment]
On Mon, Apr 29, 2013 at 06:53:53AM -0700, Matt Davis wrote:

> And another option I just found out about, similar to pythonxy:
> https://code.google.com/p/winpython/.

I think the most important thing here is to guess which route will
attract the most development going forward.  It looks like WinPython
is just Pierre Raybaut, although he seems to be a fairly active fellow
;).

**Comment by goxberry** [comment]
To follow up on this dormant thread, Continuum has just released Anaconda 1.5.0, and they've added a prompt to their installer where users are asked if they want to add Anaconda to their `PATH`.

Another nice thing about their installation process, if you're an instructor, is that you can run Anaconda as if it were a virtualenv; within the Anaconda install directory is a script `bin/activate`, which acts a lot like virtualenv, and will automatically add the Anaconda install directory to your `PATH` when you `source` it. Then `source bin/deactivate` will remove it from your `PATH`. (This feature was also available in Anaconda 1.4.) That way, instructors don't have to mess with their software stacks, and can run Anaconda in a sandboxed fashion, while students can automatically install Anaconda so that it "just works" more permanently.

I don't know how it runs in Windows yet; I work in Linux and OS X, and it works nicely in those environments.

Thanks, @teoliphant, and keep up the good work!
