### ISSUE TITLE
XML related build error

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-website#495]
I'm getting this error trying to build the website:

```
Traceback (most recent call last):
  File "bin/compile.py", line 948, in <module>
    main(sys.argv[1:])
  File "bin/compile.py", line 940, in main
    create_rss(app.blog_filename, app.site, BlogPostPage.Instances)
  File "bin/compile.py", line 905, in create_rss
    rss.write_xml(writer)
  File "/Users/jiffyclub/projects/swc-website/bin/PyRSS2Gen.py", line 73, in write_xml
    self.publish(handler)
  File "/Users/jiffyclub/projects/swc-website/bin/PyRSS2Gen.py", line 419, in publish
    item.publish(handler)
  File "/Users/jiffyclub/projects/swc-website/bin/PyRSS2Gen.py", line 468, in publish
    self.publish_extensions(handler)
  File "bin/compile.py", line 807, in publish_extensions
    handler._out.write('<%(e)s><![CDATA[%(c)s]]></%(e)s>' %
AttributeError: XMLGenerator instance has no attribute '_out'
make[1]: *** [check-bare] Error 1
make: *** [check] Error 2
```

Ideas?

**Comment by jiffyclub** [comment]
It's been a month or so since I built the site. I think the only difference is that I've upgraded to Python 2.7.4.

**Comment by pipitone** [comment]
Yeah... Okay, I see what the problem is.

handler._out.write(...) is a hack I wedged in so that we could dump out the
raw HTML content of posts as CDATA sections in the RSS.  handler is a
xml.sax.saxutils.XMLGenerator class and doesn't publicly expose a method to
dump out unescaped XML content (e.g. a CDATA section). I was accessing the
private member _out to do my dirty work.

In Python 2.7.4, _out no longer exists[1], hence the error you're seeing,
Matt.

Possible solutions:
1. Use handler._write(...) since that will work in both versions...  but
it's still a hack unworthy of a true computer scientist, and liable to
break in future/past versions.
2. Fix PyRSS so that it depends on something other than XMLGenerator...
something that allows us to write CDATA sections.
3. Switch to another RSS library that let's us write CDATA sections

[1] In Python 2.7.3:
http://hg.python.org/cpython/file/70274d53c1dd/Lib/xml/sax/saxutils.py
In Python 2.7.4:
http://hg.python.org/cpython/file/026ee0057e2d/Lib/xml/sax/saxutils.py

**Comment by drj11** [comment]
On 19 April 2013 13:17, Jon Pipitone notifications@github.com wrote:

> Yeah... Okay, I see what the problem is.
> 
> handler._out.write(...) is a hack I wedged in so that we could dump out the
> raw HTML content of posts as CDATA sections in the RSS. handler is a
> xml.sax.saxutils.XMLGenerator class and doesn't publicly expose a method to
> dump out unescaped XML content (e.g. a CDATA section). I was accessing the
> private member _out to do my dirty work.
> 
> In Python 2.7.4, _out no longer exists[1], hence the error you're seeing,
> Matt.

Hmm.

Instead of including the HTML as a CDATA section, have you considered
escaping the HTML so it's a valid XML string?

http://docs.python.org/2/library/xml.sax.utils.html#xml.sax.saxutils.escape

should do the trick.

drj

**Comment by pipitone** [comment]
> Instead of including the HTML as a CDATA section, have you considered
> escaping the HTML so it's a valid XML string?

Yes, this is what the handler does by default when you try to write text to
an XML node. It's what we want to _avoid_ when we're writing out the HTML
content though, because RSS readers expect content:encoded elements to
contain a CDATA with unescaped HTML.

See here:
https://developer.mozilla.org/en-US/docs/RSS/Article/Why_RSS_Content_Module_is_Popular_-_Including_HTML_Contents

**Comment by drj11** [comment]
No-one respects that XML is XML. web collapses.

_sigh_

RSS readers aren't supposed to be able to tell the difference between
something that's been escaped and something that's including as CDATA.

Oh well.

drj
