### ISSUE TITLE
Add TOC of names for easier navigation

### ISSUE THREAD

**Issue by karthik** [swcarpentry/DEPRECATED-website#60]
On [this page](http://dev.software-carpentry.org/about/team.html), the list of instructors is quite long. It would make it easier to navigate with a list of names up top that link to anchors down below.

**Comment by caitsydney** [comment]
I'm trying to learn how to do this, using the TOC here as a template: http://dev.software-carpentry.org/4_0/index.html

Not sure what page.children means... But I think I could get this working pretty quickly if someone explained it to me. Also not sure how/where to put the instructor info. If you want the TOC to update whenever you add new instructors, would each instructor need their own file in some subdirectory? 

A link to a web tutorial would be sufficient to get me started on this. I see @gvwilson is already assigned, so maybe looking at this problem is redundant. It just caught my attention and now I want to learn how to do it.

<h2>Instructors</h2>

<div class="toc">
    <h4>Contents</h4>
    <ul>
        {% for instructor in page.children %}
        <li> <a href="#{{instructor.slug}}">{{instructor.name}}</a></li>
    </ul>
</div>

{% for instructor in page.children %}

<div id="{{instructor.slug}}">
    <div class="media">
        <img class="media-object pull-left" src="{{root_path}}/img/people/{{instructor.name}}.jpg" alt="{{instructor.name}}" />
        <div class="media-body"> {{instructor.html}} </div>
    </div>
</div>

{% endfor %}

**Comment by gvwilson** [comment]
We're using Jinja2 as a templating engine: http://jinja.pocoo.org/docs/. 
  There are also docs in swc/5.0/website/bin/compile.py, and I'm happy 
to answer questions.

**Comment by jiffyclub** [comment]
Based on http://software-carpentry.org/about/team.html it looks like @gvwilson took care of this.

**Comment by gvwilson** [comment]
Yup.
