### ISSUE TITLE
Create and issue 'helper' badges

### ISSUE THREAD

**Issue by embray** [swcarpentry/DEPRECATED-website#628]
A couple bootcamps I've been in recently have had some very, very excellent helpers come out and volunteer their time to help out for the entire bootcamp.  Many if not most of them would also be qualified to teach (though simply have not yet).  In the meantime we should definitely award them badges for their efforts.  See also #157.

**Comment by embray** [comment]
I think even just one would be enough if they were helpful enough.  For example Terri Yu has now helped at a couple, I think, but she should definitely get a badge even for the first one.  I can think of others too.

It would be hard to define exact criteria so maybe just say one of the bootcamp instructors should "nominate" them to receive the badge.

**Comment by ethanwhite** [comment]
On Tue, Jul 2, 2013 at 8:24 AM, Erik Bray notifications@github.com wrote:

> I think even just one would be enough if they were helpful enough. For
> example Terri Yu has now helped at a couple, I think, but she should
> definitely get a badge even for the first one. I can think of others too.
> 
> It would be hard to define exact criteria so maybe just say one of the
> bootcamp instructors should "nominate" them to receive the badge.

Instead of having this difficult to judge (and therefore open to bias)
idea of "helpful enough" I'd suggest that we simply award the badge to
anyone who has been a helper for two full days. This could either be
helping for an entire workshop, or half of two different workshops,
etc. Alternatively it could just be having helped with a single full
workshop on both days.

Ethan

**Comment by gvwilson** [comment]
Moved to new website.
